version: "3"
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=ecommerce
    ports:
      - "3306:3306"
    volumes:
      - "C:/Users/Franco/Documents/TUDAI/Arquitecturas/ArquitecturaWebGrupo1/Integrador 1/EjercicioIntegrador1:/var/lib/mysql"
